<a href="https://colab.research.google.com/github/pkmariya/Python/blob/main/Int_Preps_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
v1 = [4, 8, 9, 11]
v2 = [0, 1, -1, 20]


In [ ]:
def distance(v1, v2):
  dist = 0
  v1 = np.array(v1)
  v2 = np.array(v2)
  dist = np.sum(np.square(v1-v2))
  return dist

In [ ]:
result = np.sqrt(distance(v1, v2))
print(result)


15.684387141358123


In [ ]:
# another simple way
print(sum((np.array(v1) - np.array(v2))**2) ** 0.5)

15.684387141358123


In [ ]:
all_points = [[1, 2, 3, 4], [2, 3, 0, -4], [-1, 4, 1, 0], [0, 1, 2, 5], [1, 10, 0, 0], [0,0,0,0]]
current_point = [4, 1, 0, 3]

In [ ]:
def dist(a, b):
  res = 0
  p1 = np.array(a)
  p2 = np.array(b)
  res = np.sum(np.square(p1-p2))**0.5
  return res

In [ ]:
for i in range(len(all_points)):
  print(dist(i, current_point))

5.0990195135927845
3.7416573867739413
3.1622776601683795
3.7416573867739413
5.0990195135927845
6.782329983125268


In [ ]:
np.sum((np.array(all_points) - np.array(current_point))**2,axis=1)**0.5

array([4.47213595, 7.54983444, 6.63324958, 4.89897949, 9.94987437,
       5.09901951])

### Diff b/w Identity Matrix and Diagnol matrix

In [11]:
# Identity Matrix
iden_matrix = np.eye(5)
iden_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
# Diagnol Matrix
diag_matrix = np.diag([1, 2, 3, 4, 5])
diag_matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### Diff b/w Repeat and Tile

In [9]:
# Repeat the elements
arr = [0, 1, 2]
rep_arr = np.repeat(arr, 3)
rep_arr

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [10]:
# Repeat the Rows
arr = [0, 1, 2]
tile_arr = np.tile(arr, 3)
tile_arr

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [13]:
# Random array - random function typically gives random numbers b/w 0 to 1
ran_arr = np.random.rand(3)
ran_arr

array([0.42968459, 0.72474237, 0.86414822])

In [14]:
ran_arr1 = np.random.rand(3,3)
ran_arr1

array([[0.53317228, 0.01629626, 0.19472516],
       [0.7543154 , 0.9678279 , 0.99807502],
       [0.61505981, 0.73377186, 0.74029029]])

In [18]:
# To print random numnbers other than b/w 0 to 1. This prints 4 random numbers b/w 1 to 10
random_ints = np.random.randint(1, 10, 4)
random_ints

array([4, 5, 3, 3])

In [19]:
np.sum(random_ints)

15

In [15]:
# To retrieve just the diagnoal elements from a matrix
np.diag(ran_arr1)

array([0.53317228, 0.9678279 , 0.74029029])

In [23]:
# Count unique values in an array

uniq_arr = np.array([1, 2, 3, 2, 1, 3, 4, 6, 5, 5, 6])
uniques, counts = np.unique(uniq_arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 2 2]


In [83]:
def count_unique(a):
  for i in range(len(a)):
    count = 0
    for ele in a:
      if (ele == a[i]):
        count = count + 1
    print(a[i], end=' ')
    print(count, end=' ')
    print()

In [84]:
inp_arr = [1, 2, 3, 2, 1, 3, 4, 1, 6, 5, 5, 6]
count_unique(inp_arr)

1 3 
2 2 
3 2 
2 2 
1 3 
3 2 
4 1 
1 3 
6 2 
5 2 
5 2 
6 2 


In [59]:
print(inp_arr.count(3))

2
