<a href="https://colab.research.google.com/github/pkmariya/Python/blob/main/Loan_Assign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as st

In [2]:
loan_df = pd.read_csv('https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/018/746/original/loan.csv?1666170299')

In [3]:
loan_df['Loan_Amount_per_year'] = loan_df['LoanAmount'] / loan_df['Loan_Amount_Term']

In [4]:
data = loan_df.copy()

In [5]:
# group1 women data
group1 = data[(data['Gender']=='Female')]['Loan_Amount_per_year']

In [6]:
# group2 unmarried men data
group2 = data[(data['Gender']=='Male') & (data['Married']=='No')]['Loan_Amount_per_year']

In [7]:
group1.var()

0.22548316632557983

In [8]:
group2.var()

0.11362377496532253

In [9]:
# dropping the missing values of both the groups
group1 = group1.dropna()
group2 = group2.dropna()

In [10]:
print("Number of records in group1 (Women): ", len(group1))
print("Variance of group1 (Women): ", round(group1.var(),2))
print("Number of records in group2 (Men): ", len(group2))
print("Variance of group2 (Men): ", round(np.var(group2),2))

Number of records in group1 (Women):  106
Variance of group1 (Women):  0.23
Number of records in group2 (Men):  123
Variance of group2 (Men):  0.11


In [11]:
p_val_ttest = st.ttest_ind(group1, group2)[1]

In [12]:
p_val_kruskal = st.kruskal(group1, group2)[1]

In [13]:
print("Kruskal test p_value is: ", round(p_val_kruskal, 2))

Kruskal test p_value is:  0.11


In [14]:
alpha = 0.05
if p_val_kruskal < alpha:
  print("Since p_value is less than Alpha, we fail to accept the Null Hypothesis")
else:
  print("Since p_value is greater than Alpha, we fail to reject the Null Hypothesis")

Since p_value is greater than Alpha, we fail to reject the Null Hypothesis


In [15]:
loan_rejected_df1 = loan_df[loan_df['Loan_Status']=='N']

In [16]:
loan_rejected_df1.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       192.000000         192.000000  181.000000        186.000000   
mean       5446.078125        1877.807292  151.220994        344.064516   
std        6819.558528        4384.060103   85.862783         69.238921   
min         150.000000           0.000000    9.000000         36.000000   
25%        2885.000000           0.000000  100.000000        360.000000   
50%        3833.500000         268.000000  129.000000        360.000000   
75%        5861.250000        2273.750000  176.000000        360.000000   
max       81000.000000       41667.000000  570.000000        480.000000   

       Credit_History  Loan_Amount_per_year  
count      179.000000            175.000000  
mean         0.541899              0.492564  
std          0.499639              0.436674  
min          0.000000              0.025000  
25%          0.000000              0.288889  
50%          1.000000              0.375000  
75%          1.000000              0.541667  
max          1.000000              4.305556

In [17]:
from scipy.stats import chi2_contingency

In [18]:
val = pd.crosstab(index=loan_rejected_df1["Gender"]=='Male', columns=loan_rejected_df1["Credit_History"]=="1").values
print(val)
chi2_contingency(val) # chi_stat, p_value, df, expected_values = 

[[ 42]
 [150]]


(0.0, 1.0, 0, array([[ 42.],
        [150.]]))

In [19]:
val = pd.crosstab(index=loan_df["Gender"]=='Male', columns=loan_df["Loan_Status"]=="Yes").values
print(val)
chi2_contingency(val) # chi_stat, p_value, df, expected_values = 

[[125]
 [489]]


(0.0, 1.0, 0, array([[125.],
        [489.]]))

In [20]:
cc_df = loan_df[loan_df['Credit_History']==1]

In [21]:
cc_df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
608  LP002974    Male     Yes          0      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
608             3232             1950.0       108.0             360.0   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   

     Credit_History Property_Area Loan_Status  Loan_Amount_per_year  
0               1.0         Urban           Y                   NaN  
1               1.0         Rural           N              0.355556  
2               1.0         Urban           Y              0.183333  
3               1.0         Urban           Y              0.333333  
4               1.0         Urban           Y              0.391667  
..              ...           ...         ...                   ...  
608             1.0         Rural           Y              0.300000  
609             1.0         Rural           Y              0.197222  
610             1.0         Rural           Y              0.222222  
611             1.0         Urban           Y              0.702778  
612             1.0         Urban           Y              0.519444  

[475 rows x 14 columns]

In [23]:
val1 = pd.crosstab(index=cc_df["Gender"]=='Male', columns=cc_df["Loan_Status"]=="Yes").values
print(val1)
chi2_contingency(val1) # chi_stat, p_value, df, expected_values = 

[[ 93]
 [382]]


(0.0, 1.0, 0, array([[ 93.],
        [382.]]))