<a href="https://colab.research.google.com/github/pkmariya/Python/blob/master/MariyaNumpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Series 01
NumPy - Numerical Python is the core library for numeric and scientific computing. 
It consists of multi-dimensional array objects and collection of routines to process them

# Different ways arrays created using NumPy


1.   One dimensional Array 
      *   np.array([1, 10, 15, 20])
      
2.   Two dimensional Array
      *   np.array ([[1, 2, 3],[4, 5, 6]])

3.   Zeros Array
      *   np.zeros((3, 3))

4.   An Array with a given number
      *   np.full((3, 3), 10)

5.   Array with a Range
      *   np.arange(1, 10)

6.   Array Range with Step value
      *   np.arange(10, 100, 10)

7.   Random Array 
      *   np.random.randint(10, 50)

8.   Random Array with number of values
      *   np.random.randint(10, 50, 5)



In [3]:
import numpy as np

# Creating Arrays using NumPy routines

In [ ]:
# Single dimensional numpy array
SingleDimArray = np.array([10, 20, 30, 40, 50])
SingleDimArray

array([10, 20, 30, 40, 50])

In [ ]:
# Two dimensional numpy array
TwoDimArray = np.array([[10, 20, 30, 40], [40, 30, 20, 10]])
TwoDimArray

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [ ]:
# Initialize numpy array with zeros OR create an array of zeros
ZerosArray = np.zeros((3, 2))
ZerosArray


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# Shape of an Array
np.shape(ZerosArray)

(3, 2)

In [ ]:
# Initialize numpy array with a given number
SameNumArray = np.full((3, 2), 10)
SameNumArray

array([[10, 10],
       [10, 10],
       [10, 10]])

In [ ]:
# Create an array with a range
ArraywithRange = np.arange(1, 10)
ArraywithRange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create an array range with Step value
ArrayRangewithStep = np.arange(100, 200, 10)
ArrayRangewithStep

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [ ]:
# Create an array with random numbers
RandomArray = np.random.randint(10, 50)
RandomArray

16

In [ ]:
# Number of random values
RandomArrayValues = np.random.randint(10, 50, 3)
RandomArrayValues

array([48, 33, 25])

# NumPy Array Shape and reshape

In [6]:
# Array Shape and changing the dims using shape method
OriginalArray = np.array([[10, 20, 30], [40, 50, 60]])
OriginalArray

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
# Shape of the original array is: 
OriginalArray.shape

(2, 3)

In [8]:
# now changing the above 2x3 array to 3x2
OriginalArray.shape = (3, 2)
OriginalArray

array([[10, 20],
       [30, 40],
       [50, 60]])

In [9]:
OriginalArray.shape

(3, 2)

# Numpy Array Joins
*   vstack
*   hstack
*   column_stack


In [11]:
# Vertical Stacking or Row-wise Join
firstArray = np.array([10, 20, 30])
secondArray = np.array([40, 50, 60])
VStackedArray = np.vstack((firstArray, secondArray))
VStackedArray

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
# Horizontal Stacking
oneArray = np.array([10, 20, 30])
twoArray = np.array([40, 50, 60])
HStackedArray = np.hstack((oneArray, twoArray))
HStackedArray

array([10, 20, 30, 40, 50, 60])

In [13]:
# Column-wise Stacking or Join; first array becomes first column and second array becomes second column 
colStack = np.column_stack((oneArray, twoArray))
colStack

array([[10, 40],
       [20, 50],
       [30, 60]])

# NumPy arrays Intersection & Difference

In [18]:
# Intersection 

n1 = np.array([10, 20, 30, 40, 50, 60, 70])
n2 = np.array([10, 20, 90])
IntersectArray = np.intersect1d(n1, n2)
IntersectArray

array([10, 20])

In [19]:
# Array difference

diffArray = np.setdiff1d(n1, n2)
diffArray

array([30, 40, 50, 60, 70])

In [20]:
diffArray1 = np.setdiff1d(n2, n1)
diffArray1

array([90])

# NumPy array Mathematics


*   np.sum([arr1, arr2]) - total sum of all values
*   np.sum([arr1, arr2], axis=0) - column-wise sum of each element
*   np.sum([arr1, arr2], axis=1) - row-wise sum

# Scaler arithmetic operations
*   arr1 + 10         # simple addition
*   arr1 - 10         # simple subtraction
*   arr1 * 10         # simple multiplication
*   arr1 / 10         # simple division


In [24]:
# Sum of all the elements
n1 = np.array([5, 15, 25])
n2 = np.array([10, 20, 30])
sumOfArrays = np.sum([n1, n2])
sumOfArrays

105

In [25]:
# column-wise sum of individual elements
n1 = np.array([5, 15, 25])
n2 = np.array([10, 20, 30])
sumOfArrays = np.sum([n1, n2], axis=0)
sumOfArrays

array([15, 35, 55])

In [26]:
# Row-wise sum
n1 = np.array([5, 15, 25])
n2 = np.array([10, 20, 30])
sumOfArrays = np.sum([n1, n2], axis=1)
sumOfArrays

array([45, 60])

In [28]:
# basic addition with numeral
n1 = np.array([5, 10, 15])
arrayAddition = n1 + 10
arrayAddition

array([15, 20, 25])

In [33]:
# basic subtraction
n1 = np.array([10, 20, 30])
arraySubtraction = n1 - 5
arraySubtraction

array([ 5, 15, 25])

In [29]:
# basic multipliciation
n1 = np.array([5, 10, 15])
arrayMultiplication = n1 * 2
arrayMultiplication

array([10, 20, 30])

In [32]:
# basic division
n1 = np.array([10, 20, 30])
arrayDivision = n1/2
arrayDivision

array([ 5., 10., 15.])

# Mean, Median, Standarad Deviation

In [42]:
# Mean of an array
n1 = np.array([10, 20, 30, 40, 100])
arrayMean = np.mean(n1)
arrayMean

40.0

In [43]:
# Median of an array
arrayMedian = np.median(n1)
arrayMedian

30.0

In [44]:
# Standard Deviation of an array
arrayStd = np.std(n1)
arrayStd

31.622776601683793