<a href="https://colab.research.google.com/github/pkmariya/Python/blob/master/MariyaNumpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Series 01
NumPy - Numerical Python is the core library for numeric and scientific computing. 
It consists of multi-dimensional array objects and collection of routines to process them

# Different ways arrays created using NumPy


1.   One dimensional Array 
      *   np.array([1, 10, 15, 20])
      
2.   Two dimensional Array
      *   np.array ([[1, 2, 3],[4, 5, 6]])

3.   Zeros Array
      *   np.zeros((3, 3))

4.   An Array with a given number
      *   np.full((3, 3), 10)

5.   Array with a Range
      *   np.arange(1, 10)

6.   Array Range with Step value
      *   np.arange(10, 100, 10)

7.   Random Array 
      *   np.random.randint(10, 50)

8.   Random Array with number of values
      *   np.random.randint(10, 50, 5)



In [1]:
import numpy as np

In [2]:
# Single dimensional numpy array
SingleDimArray = np.array([10, 20, 30, 40, 50])
SingleDimArray

array([10, 20, 30, 40, 50])

In [4]:
# Two dimensional numpy array
TwoDimArray = np.array([[10, 20, 30, 40], [40, 30, 20, 10]])
TwoDimArray

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [14]:
# Initialize numpy array with zeros OR create an array of zeros
ZerosArray = np.zeros((3, 2))
ZerosArray


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
# Shape of an Array
np.shape(ZerosArray)

(3, 2)

In [19]:
# Initialize numpy array with a given number
SameNumArray = np.full((3, 2), 10)
SameNumArray

array([[10, 10],
       [10, 10],
       [10, 10]])

In [20]:
# Create an array with a range
ArraywithRange = np.arange(1, 10)
ArraywithRange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Create an array range with Step value
ArrayRangewithStep = np.arange(100, 200, 10)
ArrayRangewithStep

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [27]:
# Create an array with random numbers
RandomArray = np.random.randint(10, 50)
RandomArray

16

In [28]:
# Number of random values
RandomArrayValues = np.random.randint(10, 50, 3)
RandomArrayValues

array([48, 33, 25])